
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS `Asset` (
	`AssetID`     INTEGER PRIMARY KEY,
	`Name`        TEXT NOT NULL,
	`Description` TEXT NOT NULL,
	`Price`       REAL NOT NULL,
	`StockAmount` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS `SalesRecord` (
	`SaleID`    INTEGER PRIMARY KEY AUTOINCREMENT,
	`Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`AmountPaidCash` REAL NOT NULL,
	`AmountPaidEftpos` REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS `SalesAssets` (
	`SaleID`    INTEGER,
	`AssetID`   INTEGER,
	`Qty`       INTEGER NOT NULL,
	FOREIGN KEY(`SaleID`) REFERENCES `SalesRecord`(`SaleID`),
	PRIMARY KEY(`SaleID`,`AssetID`),
	FOREIGN KEY(`AssetID`) REFERENCES `Asset`(`AssetID`)
);

COMMIT;
